/**
 *
 * Author: Auto-generated by amplify (Bashiir)
 * Jira Task:
 * Description: The component code for secure. (not used)
 *
 **/

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-secure',
  templateUrl: './secure.component.html',
  styleUrls: ['./secure.component.css']
})
export class SecureComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
