/**
 *
 * Author: Autho-generated by amplify (Bashiir)
 * Jira Task: N/A
 * Description: Component for the Authorization in the app (not used).
 *
 **/
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.css']
})
export class AuthComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
