// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:7903f87e-8141-4d7b-86ff-cf5bdd942059",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_TonoYZaSY",
  aws_user_pools_web_client_id: "34osghte5cfsg8iktmilk6gbg0"
};

export default awsmobile;
